### ISSUE TITLE
关于权重的。

### ISSUE THREAD

**Issue by newbieonCV** [taishan1994/pytorch_triple_extraction#7]
{0: 'O', 1: 'B-object', 2: 'I-object', 3: 'B-subject', 4: 'I-subject'}
Namespace(adam_epsilon=1e-08, bert_dir='../model_hub/chinese-roberta-wwm-ext/', crf_lr=0.03, data_dir='../data/', dropout=0.3, dropout_prob=0.3, eval_batch_size=32, gpu_ids='0', log_dir='./logs/', lr=3e-05, lstm_hidden=128, max_grad
_norm=1.0, max_seq_len=300, num_layers=1, num_tags=5, other_lr=0.0003, output_dir='./checkpoints/', seed=123, swa_start=3, train_batch_size=32, train_epochs=1, use_crf='True', use_lstm='True', warmup_proportion=0.1, weight_decay=0.0
1)
Some weights of the model checkpoint at ../model_hub/chinese-roberta-wwm-ext/ were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNo
rm.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).     
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).        
E:\Anoconda64\envs\seq\lib\site-packages\torch\nn\modules\rnn.py:62: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_lay
ers=1
  warnings.warn("dropout option adds dropout after all but last "
Use single gpu in: ['0']
E:\Anoconda64\envs\seq\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, 
or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

**Comment by taishan1994** [comment]
> 博主，请问怎么改才能只用cpu运行，然后就是再预测的时候，显示Traceback (most recent call last): File "main.py", line 254, in bertForNer.predict(raw_text, model_path) File "main.py", line 158, in predict model, device = trainUtils.load_model_and_parallel(model, self.args.gpu_ids, model_path) File "F:\三元组抽取的方法\pytorch_triple_extraction-main\pytorch_triple_extraction-main\bert_bilstm_crf_ner\utils\trainUtils.py", line 97, in load_model_and_parallel model.load_state_dict(torch.load(ckpt_path, map_location=torch.device('cpu')), strict=strict) File "E:\Anoconda64\envs\seq\lib\site-packages\torch\serialization.py", line 699, in load with _open_file_like(f, 'rb') as opened_file: File "E:\Anoconda64\envs\seq\lib\site-packages\torch\serialization.py", line 231, in _open_file_like return _open_file(name_or_buffer, mode) File "E:\Anoconda64\envs\seq\lib\site-packages\torch\serialization.py", line 212, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/bert_bilstm_crf/model.pt' (seq) PS F:\三元组抽取的方法\pytorch_triple_extraction-main\pytorch_triple_extraction-main\bert_bilstm_crf_ner>

torch.device("cuda" if torch,cuda.is_available() else "cpu")
会自己判断使用GPU还是CPU，加载预测的时候如果要使用cpu，需要在torch.load(path, map_location=torch.device("cpu"))。你上面保存是没有将保存的模型放在那下面。
